# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Karkul's Blog
tagline:          Just another simple blog
url:              http://karkul.github.io
paginate:         1
baseurl:          /
