# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Raymond's Blog
tagline:          A simple technical blog to keep my findings
url:              http://karkul.github.io
paginate:         1
baseurl:          /
author:
  name:           Ramon Morales
  url:            https://twitter.com/karkull
  email:          karkul@gmail.com

pages_list:
    About:        '/about'
    Archive:      '/archive'
