# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Karkul's Memories
tagline:          Just another stupid karkul's blog
url:              http://karkul.github.io
paginate:         1
baseurl:          /
author:
  name:           Ramon Morales
  url:            https://twitter.com/karkull
  email:          karkul@gmail.com

jekyllurl:        http://jekyllrb.com
