# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Karkul's Memories
tagline:          Just another stupid karkul's blog
url:              http://karkul.github.io
paginate:         1
baseurl:          /
